### ISSUE TITLE
Implement "Movie" Class to use

### ISSUE THREAD

**Issue by robotcorner** [robotcorner/CS-321-JavaTeamProjectTeam10#22]
![image](https://user-images.githubusercontent.com/20550117/160459370-b08860f5-a5be-4ada-a789-70ebf8e85ebd.png)

**Comment by robotcorner** [comment]
I would like multiple people to review and comment if this is done or needs updates.

**Comment by dandeto** [comment]
Looks good to me (LGTM). When I work on the JSON stuff I'll update it if need be. Are we expected to write a getters for each property?
