### ISSUE TITLE
Implement "MovieList" Class

### ISSUE THREAD

**Issue by robotcorner** [robotcorner/CS-321-JavaTeamProjectTeam10#26]
![image](https://user-images.githubusercontent.com/20550117/160460754-afab0e1f-1e28-43b7-9726-9f24189da83f.png)

**Comment by dandeto** [comment]
Renamed MovieList to MovieManager. Added a search method. We can make more if needed. I don't think it should be used for sorting, because it takes 1 line to sort lists, but I stubbed out a few just in case that is what we want to do.
