### ISSUE TITLE
Implement "Rating" Class

### ISSUE THREAD

**Issue by robotcorner** [robotcorner/CS-321-JavaTeamProjectTeam10#30]
![image](https://user-images.githubusercontent.com/20550117/160461445-c9e20cfa-42b6-460d-b303-feeeacac5e99.png)

**Comment by dandeto** [comment]
Can someone bring me up to speed on this? I thought we were doing favorites instead.

**Comment by robotcorner** [comment]
This was supposed to be part of the custom functionality requirement I thought.

**Comment by robotcorner** [comment]
Creating new issue related to global favorites count instead.
