### ISSUE TITLE
Implement "User" Class

### ISSUE THREAD

**Issue by robotcorner** [robotcorner/CS-321-JavaTeamProjectTeam10#32]
![image](https://user-images.githubusercontent.com/20550117/160461608-f207ce28-9a57-48d5-96d5-f1300d7fa3ac.png)

**Comment by robotcorner** [comment]
I believe @CalebBagwell recent commit work will need further improvement regarding the password system. Consult with @dandeto . We do want to make sure it's a single responsibility system with collaborator classes when necessary. You've achieved that so far, so good job with that. If we could update the commit message and tag this use case, that would be helpful for others too. Sorry that the issue system was not set up yet.

**Comment by dandeto** [comment]
I renamed `createUser` to `signup`, `logInUser` to `login`, and `logoutUser` to `logout`. I think this naming convention will better match the gui and is more intuitive. Made good progress. Added to the Test file.
