### ISSUE TITLE
Implement "UserView" Class

### ISSUE THREAD

**Issue by robotcorner** [robotcorner/CS-321-JavaTeamProjectTeam10#33]
![image](https://user-images.githubusercontent.com/20550117/160461658-39d62f6b-d9d8-4e72-821e-db8ddb1484ea.png)

**Comment by robotcorner** [comment]
I believe that the current implementation has confused UserView and LoginView. Please reply whether you believe this to be true/false. From my perspective, we were trying to allow an login/signup view, which we have made great progress on, and also allow a user to check there account credentials as another view. I though UserView was the latter, and the LoginView the former. The code has the login process as the UserView class though...

**Comment by CalebBagwell** [comment]
> I believe that the current implementation has confused UserView and LoginView. Please reply whether you believe this to be true/false. From my perspective, we were trying to allow an login/signup view, which we have made great progress on, and also allow a user to check there account credentials as another view. I though UserView was the latter, and the LoginView the former. The code has the login process as the UserView class though...

Yes, based on what you had just described, UserView should actually be called LoginView. I think I called it UserView, because it was related to the user, but LoginView makes way more sense. Do you want me to change the name of the class?

**Comment by robotcorner** [comment]
> Do you want me to change the name of the class?

Yes please.
