### ISSUE TITLE
As a user I want click an icon so that I can favorite a movie and save it to a special "favorites" list that is attached to my account

### ISSUE THREAD

**Issue by robotcorner** [robotcorner/CS-321-JavaTeamProjectTeam10#7]
#### Estimation of Effort

- TBD

#### Flow - from planning stage

Use Case 4: User Favorites a Movie
Pre-condition: user on app
Trigger: user selects ‘star icon’

_Flow 1 (typical):_
  1. The user enjoyed a movie and wants to favorite it
  2. After searching for the movie, he clicks the favorite button
  3. The movie’s favorite count increases by one
  4. The user’s account in the database records that he has favorited this movie

_Variation 1_
  4.2 User is not logged in
  4.2a In Step 2, the app redirects the user to the login page
  4.3a The flow terminates here. The user can try again after logging in

_Variation 2_
  4.2 The user has already favorited this movie
  4.2a In Step 3, the app decrements the movie’s favorite count
  4.3a In Step 3, the app decrements the movie’s favorite count
  4.4a The user’s account in the database removes this movie from his list of favorites

#### Acceptance Criteria

- TBD

#### Relates

- Relates to []

**Comment by robotcorner** [comment]
Make a default collection called favorites for each user. We will add and remove to this collection via the favorite icon within the app. Currently not present in app.
![image](https://user-images.githubusercontent.com/20550117/161613033-92c6f2cd-8e12-49db-90ff-a518467cbbd9.png)

**Comment by robotcorner** [comment]
As it's not a requirement by the professor, and is working "well enough" at this point we could maybe close this issue and move on. The only thing that we are missing is showing an additional label of the count of users that have favorites a movie. This would be a cool and useful feature for uses; however we should maybe move that to a separate issue and on the backlog of tasks now so that we can meet other requirements.

**Comment by dandeto** [comment]
We can close R4 and leave this open to track. Or create a third issue, that's fine. But this replaces the need for the rating list and rating class, etc. (I thought). We should really have this working to show the amount of users that favorited the movie.

**Comment by dandeto** [comment]
Aggregating the amount of favorites was our way of implementing 'user ratings.' This will fulfill the requirement that we implemented an additional feature, so let's either make a new issue for that specifically or keep this one around. I can't think of much else that would fulfil that requirement.

Apr 7, 2022 3:52:31 PM Stephen Stammen ***@***.***>:
